<?php
/**
 * @file
 * centar_translations.features.translations.inc
 */

/**
 * Implements hook_translations_defaults().
 */
function centar_translations_translations_defaults() {
  $translations = array();
  $translations['bg:default']['1063e38cb53d94d386f21227fcd84717'] = array(
    'source' => 'Remove',
    'context' => '',
    'location' => '/node/add/offer',
    'translation' => 'Премахни',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['3684f4f667e411f1c8f94b231c14bce9'] = array(
    'source' => '« first',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => '« първа',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['3b5aaf9cdd0b15effb9e8da5530e19f0'] = array(
    'source' => 'minimum cost - maximum comfort',
    'context' => '',
    'location' => '/',
    'translation' => 'Минимум разходи - максимум удобства',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['3c44406d52ea3dd9de7166769d4073a1'] = array(
    'source' => 'Add Offer',
    'context' => '',
    'location' => '/node/add/offer',
    'translation' => 'Добави Обява',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['4394c8d8e63c470de62ced3ae85de5ae'] = array(
    'source' => 'Log out',
    'context' => '',
    'location' => '/admin/config/regional/language',
    'translation' => 'Изход',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['6b9644eb953c6ae0a3ef75618256d2da'] = array(
    'source' => 'Choose an Image',
    'context' => '',
    'location' => 'sites/all/themes/cleancustom/assets/scripts/functions.js',
    'translation' => 'Избери Снимка',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['91412465ea9169dfd901dd5e7c96dd99'] = array(
    'source' => 'Upload',
    'context' => '',
    'location' => '/node/add/offer',
    'translation' => 'Добави',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['95bd7e8ac36751e435b69a103d48b32f'] = array(
    'source' => 'login/register',
    'context' => '',
    'location' => '/',
    'translation' => 'Влизане',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['9bab2cb29e9f41ed2af0cd476eb272f6'] = array(
    'source' => '‹ previous',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => '‹ предишна',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['c9bfdbcecd5ba2b1555dd41dc7350f69'] = array(
    'source' => 'add offer',
    'context' => '',
    'location' => '/',
    'translation' => 'Добави Обява',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['c9cc8cce247e49bae79f15173ce97354'] = array(
    'source' => 'Save',
    'context' => '',
    'location' => '/node/add/offer',
    'translation' => 'Публикувай Обявата',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['d95cf4ab2cbf1dfb63f066b50558b07d'] = array(
    'source' => 'My account',
    'context' => '',
    'location' => '/admin/config/regional/language',
    'translation' => 'Профил',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['e9323001f37eb444d27cbb02717a8053'] = array(
    'source' => 'next ›',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => 'следваща › ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['ea84bf7e44b4033f0c35cc6bc032468d'] = array(
    'source' => 'last »',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => 'последна » ',
    'plid' => 0,
    'plural' => 0,
  );
  return $translations;
}
