<?php
/**
 * @file
 * centar_translations.features.translations.inc
 */

/**
 * Implements hook_translations_defaults().
 */
function centar_translations_translations_defaults() {
  $translations = array();
  $translations['bg:default']['099af53f601532dbd31e0ea99ffdeb64'] = array(
    'source' => 'delete',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => 'изтрии',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['0be8406951cdfda82f00f79328cf4efc'] = array(
    'source' => 'Comment',
    'context' => '',
    'location' => '/admin/config/regional/translate',
    'translation' => 'Коментар',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['1063e38cb53d94d386f21227fcd84717'] = array(
    'source' => 'Remove',
    'context' => '',
    'location' => '/node/add/offer',
    'translation' => 'Премахни',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['1141130f0ff1284057047b05e17e63c4'] = array(
    'source' => '@count hours',
    'context' => '',
    'location' => '/admin/people',
    'translation' => '@count часа',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['13348442cc6a27032d2b4aa28b75a5d3'] = array(
    'source' => 'Search',
    'context' => '',
    'location' => '/user/1',
    'translation' => 'Търси',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['156a8ef39c5aedbd1b73f515d3e3cf7a'] = array(
    'source' => '@count weeks',
    'context' => '',
    'location' => '/user/1',
    'translation' => '@count седмици',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['16d2b386b2034b9488996466aaae0b57'] = array(
    'source' => 'History',
    'context' => '',
    'location' => '/user/1',
    'translation' => 'Информация',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['1aa668d559a3a32a44796aeee6978a59'] = array(
    'source' => 'Create new account',
    'context' => '',
    'location' => '/',
    'translation' => 'Регистрация',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['221e705c06e231636fdbccfdd14f4d5c'] = array(
    'source' => 'Your name',
    'context' => '',
    'location' => '/node/1',
    'translation' => 'Твоето име',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['239959e37b524db940db159c09984c0a'] = array(
    'source' => '- None -',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => 'Не е избрано',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['25812bf456959aa5f28dc570f341a3ba'] = array(
    'source' => 'Topic',
    'context' => '',
    'location' => '/forum/41',
    'translation' => 'Тема',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['25a04957b989168b2dd05fd9eb7a3673'] = array(
    'source' => 'Passwords match:',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'Съвпадение на паролите:',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['2fa104cdb397e386efece8c040a2e601'] = array(
    'source' => 'User account',
    'context' => '',
    'location' => '/admin/config/regional/language',
    'translation' => 'Регистрация',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['34ac805c9077c5ca6ae3565dab6ce723'] = array(
    'source' => 'Topics',
    'context' => '',
    'location' => '/forum',
    'translation' => 'Теми',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['3684f4f667e411f1c8f94b231c14bce9'] = array(
    'source' => '« first',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => '« първа',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['377313a88cd97bbf5da5c9dd0d8a677a'] = array(
    'source' => 'Upload picture',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'Качи снимка',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['3b5aaf9cdd0b15effb9e8da5530e19f0'] = array(
    'source' => 'minimum cost - maximum comfort',
    'context' => '',
    'location' => '/',
    'translation' => 'Минимум разходи - максимум удобства',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['3c42413840bf44f64389ba6ca4366592'] = array(
    'source' => 'Access denied. You must log in to view this page.',
    'context' => '',
    'location' => '/node/add/offer',
    'translation' => 'Моля, влезте в сайта с формата по долу или се регистрирайте.',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['3c44406d52ea3dd9de7166769d4073a1'] = array(
    'source' => 'Add Offer',
    'context' => '',
    'location' => '/node/add/offer',
    'translation' => 'Добави Обява',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['3d00bbbf613b717e7dd89b8f13a47218'] = array(
    'source' => 'Password reset instructions will be mailed to %email. You must log out to use the password reset link in the e-mail.',
    'context' => '',
    'location' => '/user/password',
    'translation' => 'Инструкции за смяна на парола ще бъдат изпратени на: %email. Трябва да излезете от системата за да използвате линка за новата парола.',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['438387d2814797ffa5a3f6b877ea612a'] = array(
    'source' => 'Add comment',
    'context' => '',
    'location' => '/node/3',
    'translation' => 'Добави коментар',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['4394c8d8e63c470de62ced3ae85de5ae'] = array(
    'source' => 'Log out',
    'context' => '',
    'location' => '/admin/config/regional/language',
    'translation' => 'Изход',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['492854807a274ec6d77bb1c5aff56704'] = array(
    'source' => '@count min',
    'context' => '',
    'location' => '/admin/config',
    'translation' => '@count мин',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['4c0c1142e65c10e79d44afb65db8298f'] = array(
    'source' => 'Register here',
    'context' => '',
    'location' => '/user/login?destination=node/add/offer',
    'translation' => 'Регистрирайте се тук',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['4c231e0da3eaaa6a9752174f7f9cfb31'] = array(
    'source' => 'Confirm password',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'Потвърди паролата',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['4fbd18c9eefb5827d7e9cd792f299fbc'] = array(
    'source' => 'Submitted by !username on !datetime',
    'context' => '',
    'location' => '/node/1',
    'translation' => 'От !username на !datetime ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['5dc52ca9ffdc26147075682c92a0a853'] = array(
    'source' => 'Posts',
    'context' => '',
    'location' => '/forum',
    'translation' => 'Мнения',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['5dd6278fdea1d1a53f162b209afd2ca2'] = array(
    'source' => 'Last post',
    'context' => '',
    'location' => '/forum',
    'translation' => 'Последни',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['5f26e28f4c098aea3d0578120b97e0bc'] = array(
    'source' => 'By !author @time ago',
    'context' => '',
    'location' => '/forum/55',
    'translation' => 'От !author, преди @time',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['677c8c6f8cafa3ebdd999eea7d18beda'] = array(
    'source' => 'Password strength:',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'Сила на паролата',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['6b9644eb953c6ae0a3ef75618256d2da'] = array(
    'source' => 'Choose an Image',
    'context' => '',
    'location' => 'sites/all/themes/cleancustom/assets/scripts/functions.js',
    'translation' => 'Избери Снимка',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['7042828cd5c73a74091f05a7c9513d0e'] = array(
    'source' => 'March',
    'context' => 'Long month name',
    'location' => '/admin/structure/pages/nojs/operation/node_view/handlers/node_view__offer_panel_template/content',
    'translation' => 'март',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['705fbbd6e1667845569c00fd7523d343'] = array(
    'source' => '1 week',
    'context' => '',
    'location' => '/admin/config/system/cron',
    'translation' => '1 седмица',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['70a54779aae07a17ce469c24d2a5ab73'] = array(
    'source' => 'Member for',
    'context' => '',
    'location' => '/user/1',
    'translation' => 'Регистриран от',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['72ab9d0304d3e84c6aa2dd15eda282f2'] = array(
    'source' => '1 hour',
    'context' => '',
    'location' => '/admin/config',
    'translation' => '1 час',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['7fa3b767c460b54a2be4d49030b349c7'] = array(
    'source' => 'no',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'не',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['80e0e3c5bb40b5e62149df0ce746be93'] = array(
    'source' => 'Filter by field @field of type @type.',
    'context' => '',
    'location' => '/index.php',
    'translation' => 'Филтрирай по @field of type @type.',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['878530871f0db73f004f5bd6591eeb76'] = array(
    'source' => 'Remember me',
    'context' => '',
    'location' => '/',
    'translation' => 'Запомни ме',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['8789bb39b7610c4f1b594194d9b286ba'] = array(
    'source' => 'Delete picture',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'Изтрии снимката',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['8ae5811be1a55b9b8447ad2dbdadbf6e'] = array(
    'source' => 'Picture',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'Снимка',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['8b5dd64ab8d0b8158906796b53a200e2'] = array(
    'source' => 'E-mail address',
    'context' => '',
    'location' => '/index.php',
    'translation' => 'E-mail адрес',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['8bd3d92710919bcd20487131e61b2f68'] = array(
    'source' => '@count months',
    'context' => '',
    'location' => '/admin/structure/pages/nojs/operation/node_view/handlers/node_view__offer_panel_template/content',
    'translation' => '@count месеца',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['8cc46df5ae23686a6fbb8e132f4aaf26'] = array(
    'source' => 'Replies',
    'context' => '',
    'location' => '/index.php',
    'translation' => 'Отговори',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['91412465ea9169dfd901dd5e7c96dd99'] = array(
    'source' => 'Upload',
    'context' => '',
    'location' => '/node/add/offer',
    'translation' => 'Добави',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['91de1625817dd08c1963c09c5c3371c6'] = array(
    'source' => 'Last reply',
    'context' => '',
    'location' => '/forum/41',
    'translation' => 'Последна активност',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['95bd7e8ac36751e435b69a103d48b32f'] = array(
    'source' => 'login/register',
    'context' => '',
    'location' => '/',
    'translation' => 'Влизане',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['9bab2cb29e9f41ed2af0cd476eb272f6'] = array(
    'source' => '‹ previous',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => '‹ предишна',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['a03d35bdf0359d609f5a2ab90a94404c'] = array(
    'source' => 'Not registered yet, register !url',
    'context' => '',
    'location' => '/user/login?destination=node/add/offer',
    'translation' => 'Нямате акаунт, направете си !тук',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['a0e7642fb04ea92afc1d861f614fe75a'] = array(
    'source' => '- Any -',
    'context' => '',
    'location' => '/admin/structure/views/settings',
    'translation' => 'Всички',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['a6105c0a611b41b08f1209506350279e'] = array(
    'source' => 'yes',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'да',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['a91fb167388b962082f35abd95f36193'] = array(
    'source' => '@count days',
    'context' => '',
    'location' => '/admin/people',
    'translation' => '@count дни',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['bffe9a3c9a7e00ba00a11749e022d911'] = array(
    'source' => 'Log in',
    'context' => '',
    'location' => '/',
    'translation' => 'Вход',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['c7892ebbb139886662c6f2fc8c450710'] = array(
    'source' => 'Subject',
    'context' => '',
    'location' => '/user/1',
    'translation' => 'Заглавие',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['c9bfdbcecd5ba2b1555dd41dc7350f69'] = array(
    'source' => 'add offer',
    'context' => '',
    'location' => '/',
    'translation' => 'Добави Обява',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['ca9240b03fd8c1c8efe16cdd022e7a85'] = array(
    'source' => 'Filter by @title:',
    'context' => '',
    'location' => '/search/offer/%D0%B0%D0%B2%D1%82%D0%BE',
    'translation' => 'Филтър по @title:',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['cf0cb20d90ec9b41d9a365074d49b79c'] = array(
    'source' => 'Enter your current password to change the %mail or %pass. !request_new.',
    'context' => '',
    'location' => '/user/4/edit?destination=admin/people',
    'translation' => 'Въведете паролата си, за да смените %mail или %pass. !request_new. ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['d95cf4ab2cbf1dfb63f066b50558b07d'] = array(
    'source' => 'My account',
    'context' => '',
    'location' => '/admin/config/regional/language',
    'translation' => 'Профил',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['d9c2d86a66aa5a45326c3757f3a272cc'] = array(
    'source' => 'Current password',
    'context' => '',
    'location' => '/user/32/edit',
    'translation' => 'Настояща парола',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['dc647eb65e6711e155375218212b3964'] = array(
    'source' => 'Password',
    'context' => '',
    'location' => '/',
    'translation' => 'Парола',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['dc9b851d2514e56e620240e8bad767e8'] = array(
    'source' => 'February',
    'context' => 'Long month name',
    'location' => '/admin/structure/pages/add/page-front_page_panel/content',
    'translation' => 'февруари',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['de95b43bceeb4b998aed4aed5cef1ae7'] = array(
    'source' => 'edit',
    'context' => '',
    'location' => '/admin/config/regional/language',
    'translation' => 'редактирай',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['e1bd06d422598c306c013e9c334e54a3'] = array(
    'source' => 'Request new password',
    'context' => '',
    'location' => '/',
    'translation' => 'Заявете нова парола',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['e3b481d5297f475abc283227bedbd9b9'] = array(
    'source' => '1 day',
    'context' => '',
    'location' => '/user/1',
    'translation' => '1 ден',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['e6a7f8a2f42cc35979973da8dfb10720'] = array(
    'source' => 'Forum',
    'context' => '',
    'location' => '/forum',
    'translation' => 'Форум',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['e84afaab83ecb301b3d97ce4174d2773'] = array(
    'source' => 'reply',
    'context' => '',
    'location' => '/node/3',
    'translation' => 'коментирай',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['e9323001f37eb444d27cbb02717a8053'] = array(
    'source' => 'next ›',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => 'следваща › ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['ea84bf7e44b4033f0c35cc6bc032468d'] = array(
    'source' => 'last »',
    'context' => '',
    'location' => '/admin/config/regional/translate/translate',
    'translation' => 'последна » ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['eae5ea151b88fa4d006d3588b7479d7d'] = array(
    'source' => 'Not registered yet? ',
    'context' => '',
    'location' => '/user/login?destination=node/add/offer',
    'translation' => 'Нямате акаунт? ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['eb6b06cab0dd72e04c4da68d511facf2'] = array(
    'source' => 'Search results',
    'context' => '',
    'location' => '/index.php',
    'translation' => 'Резултати',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['f0866d8d4567a04bb1620b51006a42af'] = array(
    'source' => '-Any-',
    'context' => '',
    'location' => '/index.php',
    'translation' => 'Всички',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['bg:default']['f6039d44b29456b20f8f373155ae4973'] = array(
    'source' => 'Username',
    'context' => '',
    'location' => '/',
    'translation' => 'Потребителско име',
    'plid' => 0,
    'plural' => 0,
  );
  return $translations;
}
