<?php
/**
 * @file
 * centar_simple_fb.module
 * Custom module to extend simple facebook module functionality.
 */

/**
 * Implements hook_simple_fb_connect_register_alter(&$fields, $fb_user_profile);
 */
function centar_simple_fb_simple_fb_connect_register_alter(&$fields, $fb_user_profile) {
  if (isset($fields['name']) && !empty($fb_user_profile['name'])) {
    // $fb_user_profile['name'] contains the name
    // without underscore between first and last name
    $fields['name'] = $fb_user_profile['name'];
  }
}